site_name: XRouting
docs_dir: docs
site_dir: _build/site
edit_uri: tree/master/docs

repo_name: 'Jako/xrouting'
repo_url: https://github.com/Jako/xrouting

copyright: '&copy; 2014-2023 <a href="https://seda.digital">SEDA.digital</a>'

nav:
- Description: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Contributors: 'contributors.md'

extra:
  analytics:
    provider: matomo
    url: matomo.treehillstudio.com
    site: 40
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jako

theme:
  name: material
  custom_dir: ../../mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  font: false

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - meta
  - toc
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox
